# Generated by Django 4.1.3 on 2022-11-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_payslip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='price',
            new_name='total_price',
        ),
    ]
