# Generated by Django 4.1.3 on 2022-11-11 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_price_payslip_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
